env:
  node: true
  commonjs: true
  es6: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-inner-declarations:
    - warn
  no-console:
    off
  comma-dangle:
    - error
    - always
globals:
  describe: true
  test: true
  expect: true

